{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "loadgen.fullname" . }}-deny-all
  labels: {{- include "loadgen.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels: {{- include "loadgen.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "loadgen.fullname" . }}-allow-egress
  labels: {{- include "loadgen.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels: {{- include "loadgen.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Egress
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ .Values.networkPolicy.dns.namespace | quote }}
          podSelector:
            matchLabels: {{- toYaml .Values.networkPolicy.dns.podLabels | nindent 14 }}
      ports:
        - port: 53
          protocol: UDP
        - port: 53
          protocol: TCP
    - to:
        - podSelector:
            matchLabels: {{- toYaml .Values.networkPolicy.gateway.podLabels | nindent 14 }}
      ports:
        - port: 8000
          protocol: TCP
    {{- with .Values.networkPolicy.extraEgress }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}
