apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: loki-backend-ingress
  namespace: observability
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: loki
      app.kubernetes.io/instance: loki
      app.kubernetes.io/component: single-binary
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: loki
              app.kubernetes.io/instance: loki
      ports:
        - protocol: TCP
          port: 3100
        - protocol: TCP
          port: 9095
        - protocol: TCP
          port: 7946
