config:
  clients:
    - url: http://loki-gateway.observability.svc.cluster.local/loki/api/v1/push
      tenant_id: kate
      basic_auth:
        username: kate
        password_file: /etc/loki-auth/LOKI_TENANT_PASSWORD
  snippets:
    pipelineStages:
      - cri: {}
      - json:
          expressions:
            trace_id: trace_id
            span_id: span_id
            level: level
      - labels:
          trace_id:
          span_id:
          level:

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    memory: 128Mi

extraVolumes:
  - name: loki-auth
    secret:
      secretName: loki-tenant-auth

extraVolumeMounts:
  - name: loki-auth
    mountPath: /etc/loki-auth
    readOnly: true
