apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: orders-api-staging
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/matthew-brough/Kate
    targetRevision: HEAD
    path: charts/orders-api
    helm:
      valueFiles:
        - ci/staging-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: platform-staging
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
