{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "auth-api.fullname" . }}-deny-all
  labels: {{- include "auth-api.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels: {{- include "auth-api.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "auth-api.fullname" . }}-allow-ingress
  labels: {{- include "auth-api.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels: {{- include "auth-api.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: gateway
      ports:
        - port: http
          protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "auth-api.fullname" . }}-allow-egress
  labels: {{- include "auth-api.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels: {{- include "auth-api.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Egress
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ .Values.networkPolicy.dns.namespace | quote }}
          podSelector:
            matchLabels: {{- toYaml .Values.networkPolicy.dns.podLabels | nindent 14 }}
      ports:
        - port: 53
          protocol: UDP
        - port: 53
          protocol: TCP
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: {{ include "auth-api.fullname" . }}-postgresql
      ports:
        - port: 5432
          protocol: TCP
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ .Values.networkPolicy.otel.namespace | quote }}
          podSelector:
            matchLabels: {{- toYaml .Values.networkPolicy.otel.podLabels | nindent 14 }}
      ports:
        - port: 4317
          protocol: TCP
    {{- with .Values.networkPolicy.extraEgress }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}
