{{- if .Values.jwtSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "auth-api.fullname" . }}-jwt
  labels: {{- include "auth-api.labels" . | nindent 4 }}
type: Opaque
stringData:
  jwt-secret: {{ .Values.jwtSecret | quote }}
{{- end }}
