apiVersion: v2
name: report-api
description: Report request service
type: application
version: 0.1.0
appVersion: "0.1.0"
keywords:
  - reports
  - kate
  - fastapi
maintainers:
  - name: matthew-brough

dependencies:
  - name: postgresql
    version: "16.x.x"
    repository: "https://charts.bitnami.com/bitnami"
    condition: postgresql.enabled
