apiVersion: v2
name: orders-api
description: Orders management service
type: application
version: 0.1.0
appVersion: "0.1.0"
keywords:
  - orders
  - kate
  - fastapi
maintainers:
  - name: matthew-brough
