{{- if .Values.keda.enabled }}
{{- if .Values.redisSecret.enabled }}
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: {{ include "worker.fullname" . }}-redis
  labels: {{- include "worker.labels" . | nindent 4 }}
spec:
  secretTargetRef:
    - parameter: password
      name: {{ .Values.redisSecret.name | quote }}
      key: {{ .Values.redisSecret.key | quote }}
---
{{- end }}
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ include "worker.fullname" . }}
  labels: {{- include "worker.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "worker.fullname" . }}
  minReplicaCount: {{ .Values.keda.minReplicas }}
  maxReplicaCount: {{ .Values.keda.maxReplicas }}
  cooldownPeriod: {{ .Values.keda.cooldownPeriod }}
  triggers:
    - type: redis
      metadata:
        address: {{ .Values.keda.redisAddress }}
        listName: {{ .Values.keda.queueName }}
        listLength: {{ .Values.keda.targetListLength | quote }}
        enableTLS: "false"
      {{- if .Values.redisSecret.enabled }}
      authenticationRef:
        name: {{ include "worker.fullname" . }}-redis
      {{- end }}
{{- end }}
