apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kate-staging
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/matthew-brough/Kate
    targetRevision: HEAD
    path: gitops/apps/staging
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
