apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loadgen
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/matthew-brough/Kate
    targetRevision: HEAD
    path: charts/loadgen
    helm:
      valueFiles:
        - ci/dev-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: platform
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
