# Bitnami Redis sub-chart values.
# Phase 2: standalone broker. Phase 7: chaos flag will also be stored here.
redis:
  architecture: standalone
  auth:
    enabled: false
  master:
    persistence:
      enabled: false
    resources:
      requests:
        cpu: 100m
        memory: 64Mi
      limits:
        memory: 128Mi
