name: Build

on:
  push:
    branches: [main]

permissions:
  contents: read
  id-token: write
  packages: write

jobs:
  trivy-cache:
    name: trivy cache
    runs-on: ubuntu-latest
    steps:
      - uses: aquasecurity/setup-trivy@e6c2c5e321ed9123bda567646e2f96565e34abe1 # v0.2.4
        with:
          version: v0.67.2
          cache: true

  build:
    name: ${{ matrix.service }}
    runs-on: ubuntu-latest
    needs: trivy-cache
    strategy:
      fail-fast: false
      matrix:
        service:
          - orders-api
          - auth-api
          - gateway
          - report-api
          - worker
          - loadgen
          - chaos-portal

    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f # v3

      - uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: sigstore/cosign-installer@d7543c93d881b35a8faa02e8e3605f69b7a1ce62 # v3.10.0

      - uses: docker/metadata-action@c299e40c65443455700f0fdfc63efafe5b349051 # v5
        id: meta
        with:
          images: ghcr.io/${{ github.repository_owner }}/kate-${{ matrix.service }}
          tags: |
            type=raw,value=${{ github.sha }}

      - uses: docker/build-push-action@10e90e3645eae34f1e60eeb005ba3a3d33f178e8 # v6
        id: build
        with:
          context: services/${{ matrix.service }}
          target: production
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          sbom: true
          provenance: mode=max

      - uses: aquasecurity/trivy-action@b6643a29fecd7f34b3597bc6acb0a98b03d33ff8 # v0.33.1
        with:
          image-ref: ghcr.io/${{ github.repository_owner }}/kate-${{ matrix.service }}:${{ github.sha }}
          vuln-type: os,library
          severity: HIGH,CRITICAL
          ignore-unfixed: true
          exit-code: "1"
          version: v0.67.2

      - name: Sign image
        run: cosign sign --yes ghcr.io/${{ github.repository_owner }}/kate-${{ matrix.service }}@${{ steps.build.outputs.digest }}
