{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "chaos-portal.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "chaos-portal.labels" . | nindent 4 }}
automountServiceAccountToken: true
{{- end }}
