{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "chaos-portal.fullname" . }}
  labels: {{- include "chaos-portal.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels: {{- include "chaos-portal.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: http
      path: {{ .Values.serviceMonitor.path }}
      interval: {{ .Values.serviceMonitor.interval }}
{{- end }}
